### ISSUE TITLE
Запуск на widows 10 не удался

### ISSUE THREAD

**Issue by semasping** [sergeyklay/phalcon-compose#21]
PS C:\works\docker\phalcon-compose> docker-compose up -d
phalconcompose_memcached_1 is up-to-date
phalconcompose_redis_1 is up-to-date
phalconcompose_postgres_1 is up-to-date
phalconcompose_queue_1 is up-to-date
phalconcompose_elasticsearch_1 is up-to-date
phalconcompose_mongo_1 is up-to-date
Starting phalconcompose_aerospike_1
phalconcompose_mysql_1 is up-to-date
phalconcompose_app_1 is up-to-date
```
ERROR: for aerospike  Cannot start service aerospike: invalid header field value 
"oci runtime error: container_linux.go:247: starting container process caused
"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting 
\\\\\\\"/c/works/docker/phalcon-compose/conf/aerospike/aerospike.conf\\\\\\\" to rootfs 
\\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/270479cf6fbfd4493f697da4dff4fa8c679e5c878d99c414696603eeac93a733\\\\\\\"
at \\\\\\\"/mnt/sda1/var/lib/docker/aufs/mnt/270479cf6fbfd4493f697da4dff4fa8c679e5c878d99c414696603eeac93a733/etc/aerospike/aerospike.conf\\\\\\\" 
caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
[31mERROR[0m: Encountered errors while bringing up the project.
```

**Comment by sergeyklay** [comment]
Судя по всему проблемы с Aerospike. К сожалению ребята вяло развивают продукт, на issue отвечают "раз в пол года". Я вряд ли смогу это починить быстро.  Самое быстрое решение - отключить Aerospike на Windows (просто закомментировать строки в файле `docker-compose.yml`).

**Comment by semasping** [comment]
Спасибо большое. Помогло.
